//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyobPayroll
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlip
    {
        public int PaySlipID { get; set; }
        public int EmployeeID { get; set; }
        public int MonthYearID { get; set; }
        public decimal GrossIncome { get; set; }
        public decimal IncomeTax { get; set; }
        public decimal NetIncome { get; set; }
        public decimal SuperAmount { get; set; }
        public Nullable<System.DateTime> GeneratedOn { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MonthYear MonthYear { get; set; }
    }
}
